Various enhancements
byte-physics/igor-code-browser pull request #57
Opened 2020-08-30 22:53 UTC by t-b

Close #41.

2020-09-11 10:41 UTC, MichaelHuth requested changes
It does not work correctly here:

![image](https://user-images.githubusercontent.com/29093275/92914320-d30f7c80-f42b-11ea-855f-0cb437520543.png)

The function LoadTextFile exists in ProcGlobal and in an IM. For the IM function the entry in the list looks good, but for the ProcGlobal function it shows as if it takes no parameter at all. Also with empty tooltip.

2020-09-12 21:33 UTC, t-b commented
@MichaelHuth This is an upstream IP issue. I've reported that already. The same happens with IsEmpty. Once you force recompiling of ProcGlobal it is correct. Can you confirm that?

FunctionInfo returns an empty string for the bug case, I don't see a way of working around.

2020-09-16 10:28 UTC, MichaelHuth commented
I can confirm that.

I also could not find a simple workaround for the issue.

2020-09-16 10:29 UTC, MichaelHuth approved these changes

2020-09-16 10:55 UTC, merged